import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { AntProvider } from "@/components/shared/AntProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "MemeGoat | SocialFi",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-custom-black`}>
        <AntProvider>{children} </AntProvider>
      </body>
    </html>
  )
}
